name: CI

env:
  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt-get install -y libnspr4 libnss3 libdbus-1-3 libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libc6 libcairo2 libcups2 libdrm2 libexpat1 libgbm1 libglib2.0-0 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libudev1 libuuid1 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxkbcommon0 libxrandr2 libxrender1 libxshmfence1 libxss1 libxtst6

      - run: |
          node --version
          npm --version
          npm install dotenv
          npm install puppeteer
          npm install puppeteer-autoscroll-down
          node index.js
          git config --global --add safe.directory /__w/letterboxd-profile-gen/letterboxd-profile-gen
          git config --global user.name PrideInt
          git config --global user.email 20098992+PrideInt@users.noreply.github.com
          git add -A
          git commit -m "generate image"
          git push --force
