name: CI

env:
  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22

    steps:
      - uses: actions/checkout@v4
      - run: |
          node --version
          npm --version
          npm install dotenv
          node index.js
          git config --global --add safe.directory /__w/letterboxd-profile-gen/letterboxd-profile-gen
          git config --global user.name PrideInt
          git config --global user.email 20098992+PrideInt@users.noreply.github.com
          git add -A
          git commit -m "generate image"
          git push
